---

- hosts: all
  become: true
  vars:
    fail2ban_services:
      - name: sshd
        port: "{{ ansible_port }}"
        maxretry: 7
        backend: systemd
    ufw_general_ports:
      - { port: "{{ ansible_port }}", rule: allow }
    ufw_cluster_rules: []
  tasks:
    - name: Install fail2ban
      include_role:
        name: tersmitten.fail2ban
    - name: Install unattended-upgrades
      include_role:
        name: jnv.unattended-upgrades
    - name: Install ntp
      include_role:
        name: geerlingguy.ntp
    - name: Install and setup ufw
      include_role:
        name: thomasjpfan.ufw-cluster
  tags:
    - services

- hosts: docker
  become: true
  tasks:
    - name: Install docker
      include_role:
        name: thomasjpfan.docker
    - name: Open docker ufw port if docker_swarm_manager_open
      ufw:
        port: "{{ docker_open_port }}"
        proto: tcp
        rule: allow
      when: "'docker_swarm_manager_open' in group_names"
  tags:
    - docker-install

- hosts: docker
  become: true
  vars:
    ufw_cluster_rules:
      - { port: 2377, rule: allow, proto: tcp }
      - { port: 7946, rule: allow, proto: tcp }
      - { port: 7946, rule: allow, proto: udp }
      - { port: 4789, rule: allow, proto: udp }
      - { rule: allow, proto: esp}
  tasks:
    - name: Open docker port
      include_role:
        name: thomasjpfan.ufw-cluster
    - name: Setup docker swarm
      include_role:
        name: thomasjpfan.docker-swarm
      tags:
        - docker-swarm
  tags:
    - docker-cluster

- hosts: docker
  vars_files:
    - "{{ private_root }}/deploy_cred.yml"
  tasks:
    - name: Install rexray plugin
      include_role:
        name: thomasjpfan.rexray-s3fs
  tags:
    - docker-rexray-plugin